#!/bin/bash
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/arches.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/blu_stripes.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/bright_squares.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/brushed_alu.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/circles.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/climpek.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/connect.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/corrugation.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/cubes.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/diagonal-noise.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/diagonal_striped_brick.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/diamonds.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/diamond_upholstery.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/escheresque.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/fabric_plaid.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/furley_bg.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/gplaypattern.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/gradient_squares.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/grey.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/grilled.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/hexellence.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/lghtmesh.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/light_alu.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/light_checkered_tiles.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/light_honeycomb.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/littleknobs.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/nistri.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/noise_lines.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/noise_pattern_with_crosslines.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/noisy_grid.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/norwegian_rose.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/pineapplecut.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/pinstripe.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/project_papper.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/ravenna.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/reticular_tissue.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/retina_wood.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/rockywall.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/roughcloth.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/shattered.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/silver_scales.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/skelatal_weave.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/small-crackle-bright.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/small_tiles.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/square_bg.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/struckaxiom.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/subtle_stripes.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/vichy.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/washi.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/wavecut.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/weave.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/whitey.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/wood_pattern.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/white_brick_wall.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/white_tiles.png
wget http://www.youxithemes.com/live_previews/mooncake/simple/assets/images/layout/bg/worn_dots.png

