<?php
// auto-generated by sfPropelCrud
// date: 2007/07/16 02:18:00
?>
<?php use_helper('Object') ?>

<?php echo form_tag('tag/update') ?>

<?php echo object_input_hidden_tag($tag, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User*:</th>
  <td><?php echo object_select_tag($tag, 'getUserId', array (
  'related_class' => 'User',
)) ?></td>
</tr>
<tr>
  <th>Tag*:</th>
  <td><?php echo object_input_tag($tag, 'getTag', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($tag->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'tag/delete?id='.$tag->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'tag/show?id='.$tag->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'tag/list') ?>
<?php endif; ?>
</form>
