<?php
// auto-generated by sfPropelCrud
// date: 2007/07/16 02:18:00
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $tag->getId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $tag->getUserId() ?></td>
</tr>
<tr>
<th>Tag: </th>
<td><?php echo $tag->getTag() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'tag/edit?id='.$tag->getId()) ?>
&nbsp;<?php echo link_to('list', 'tag/list') ?>
