<?php
// auto-generated by sfPropelCrud
// date: 2007/07/16 02:18:00
?>
<?php

/**
 * tag actions.
 *
 * @package    sofav
 * @subpackage tag
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class tagActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('tag', 'list');
  }

  public function executeList()
  {
    $this->tags = TagPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->tag = TagPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tag);
  }

  public function executeCreate()
  {
    $this->tag = new Tag();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->tag = TagPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tag);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $tag = new Tag();
    }
    else
    {
      $tag = TagPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($tag);
    }

    $tag->setId($this->getRequestParameter('id'));
    $tag->setUserId($this->getRequestParameter('user_id') ? $this->getRequestParameter('user_id') : null);
    $tag->setTag($this->getRequestParameter('tag'));

    $tag->save();

    return $this->redirect('tag/show?id='.$tag->getId());
  }

  public function executeDelete()
  {
    $tag = TagPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($tag);

    $tag->delete();

    return $this->redirect('tag/list');
  }
}
