<?php
// auto-generated by sfPropelCrud
// date: 2007/06/22 07:41:18
?>
<div id="postRes">
	<ul>
		<?php foreach ($posts->getResults() as $index => $post): ?>

		<li class="<?php if ($index % 2) echo 'evenRow' ?>">
		      <p class="title">
		      	<?php echo link_to($post->getTitle(), 'post/show?id=' . $post->getId(), array('target' => '_blank')) ?>
		      	<?php
		      		if ($post->getIsPrivate()) {
		      			echo image_tag('/images/1001/lock.gif', array('class' => 'icoLock', 'alt' => '私有内容，只有您自己可以看到', 'title' => '私有内容，只有您自己可以看到'));
		      		}
		      	?>

		      	<span class="author"><?php echo $post->getUser()->getUsername() ?></span>
		      </p>
		      <?php
		      	if ($post->getArrayTag()) {
		      		echo '<p class="tag">';
		      		foreach($post->getArrayTag() as $tag) {

		      			echo link_to_unless(empty($tag), $tag, 'post/show?id=' . $post->getId());
		      			echo ' ';
		      		}
		      		echo '</p>';
		      	}
		      ?>

		      <?php if ($post->getBody()) {echo '<p>' . $post->getBody() . '</p>'; } ?>
		      <p>
		      	<span class="url"><?php echo $post->getUrl() ?></span>
		      	<span class="time"><?php echo $post->getCreatedAt() ?></span>
		      	<span class="edit"><?php if ($post->getUserId() == $sf_user->getId()) echo link_to('Edit', 'post/edit?id=' . $post->getId()) ?>&nbsp;</span>
		      </p>
		</li>
		<?php endforeach; ?>

	</ul>

</div>

<?php echo include_partial('global/pageNavigation', array('pageNavigation' => $posts, 'pageUri' => 'post/list?')) ?>

<p>&nbsp;</p>
