<?php
// auto-generated by sfPropelCrud
// date: 2007/06/22 07:41:18
?>
<table cellpadding="2" cellspacing="2" border="0">
<tbody>
	<tr>
		<td colspan="2">
			<a href="<?php echo $post->getUrl() ?>" target="_blank"><?php echo $post->getTitle() ?></a>
			<?php
		      		if ($post->getIsPrivate()) {
		      			echo image_tag('/images/1001/lock.gif', array('class' => 'icoLock', 'alt' => '私有内容，只有您自己可以看到', 'title' => '私有内容，只有您自己可以看到'));
		      		}
		      	?>

		      	<?php echo $post->getUser()->getUsername() ?>

		</td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $post->getTags() ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $post->getBody() ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $post->getUrl() ?></td>
	</tr>
	<tr>
		<td>创建于 <?php echo $post->getCreatedAt() ?></td>
		<td>最后修改于 <?php echo $post->getUpdatedAt() ?></td>
	</tr>
</tbody>
</table>


<?php if ($post->getUserId() == $sf_user->getId()): ?>
<?php echo link_to('edit', 'post/edit?id='.$post->getId()) ?>
&nbsp;<?php echo link_to('list', 'post/list') ?>
<?php endif ?>
