# default rules
homepage:
  url:   /
#  param: { module: post, action: list }
  param: { module: home, action: setup }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
