default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sofav
    robots:       index, follow
    description:  网址导航, 网址收藏, 网址站, 网址大全, 导航, 收藏夹, 个性主页
    keywords:     网址导航, 网址收藏, 网址站, 网址大全, 导航, 收藏夹, 个性主页
    language:     en

  stylesheets:    [main, custom]

  javascripts:    [main]

  has_layout:     on
  layout:         layout
