<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/05/06 16:01:24
?>
<?php use_helper('ObjectDoctrineAdmin', 'Object', 'Date') ?>

<?php echo form_tag('tab/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($tab, 'getid') ?>


<table>
<tbody>
<tr>
  <th>Title: </th>
  <td>


<?php

#echo	input_tag('title', $tab->title, '');

?>

<?php

echo object_input_tag($tab, array (
  0 => 'get',
  1 =>
  array (
    0 => 'title',
  ),
), array (
  'size' => 80,
  'control_name' => 'tab[title]',
))

?>

</td>
</tr>

</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($tab->id): ?>
  &nbsp;<?php echo link_to('delete', 'tab/delete?id='.$tab->id, 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'tab/show?id='.$tab->id) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'tab/list') ?>
<?php endif; ?>
</form>
