<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/05/06 16:01:25
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $tab->getid() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $tab->gettitle() ?></td>
</tr>
</tbody>
</table>