clixxx:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage


all:
  storage:
    class: sfSessionStorage
    param:
      session_name: ssn		# sofav session name

# 使用数据库存储是为了安全，但数据库目前不支持用户名索引，所以还是用文件存储更快一点
#    class: sfMySQLSessionStorage
#    param:
#      session_name: sofav
#      auto_start:   1
#      db_table:     sf_session
#      database:     propel

#  user:
#    class: mySimpleUser

#all:
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  response:
#    class: sfWebResponse
#
#  user:
#    class: myUser
#
#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: symfony
#
#  view_cache:
#    class: sfFileCache
#    param:
#      automaticCleaningFactor: 0
#      cacheDir:                %SF_TEMPLATE_CACHE_DIR%
